function figPaths = plot_doppler_gps_ins_combined(resultFile, prnList)
% Plot requested Doppler comparisons for one scenario result:
% 1) GNSS measured Doppler vs pure INS-generated Doppler
% 2) pure INS-generated Doppler vs combined-navigation Doppler
%
% Inputs:
%   resultFile : MAT generated by run_goal1_unified_400s_insonly
%   prnList    : optional PRN list to plot (default: best 4 PRNs)
%
% Output:
%   figPaths   : generated PNG file paths

if nargin < 1 || isempty(resultFile)
    resultFile = 'rt_tight_goal1_ds5_400s_unified_ins1.mat';
end

thisDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(thisDir);
if exist(resultFile, 'file') ~= 2
    alt = fullfile(projectRoot, resultFile);
    if exist(alt, 'file') ~= 2
        error('Result file not found: %s', resultFile);
    end
    resultFile = alt;
end

S = load(resultFile);
if ~isfield(S, 'navResults') || ~isfield(S, 'settings')
    error('Result MAT must contain navResults and settings.');
end
navResults = S.navResults;
settings = S.settings;

if ~isfield(navResults, 'dopplerGpsMeasHz') || ~isfield(navResults, 'dopplerInsPredHz')
    error('Result MAT is missing Doppler fields.');
end

dop = compute_doppler_plot_series(navResults, settings);
t = dop.tSec;
gpsHz = dop.gpsRawHz;
insHz = dop.insAlignedHz;
cmbHz = dop.supAlignedHz;

if isfield(navResults, 'prnList') && ~isempty(navResults.prnList)
    prnPool = navResults.prnList(:)';
else
    prnPool = 1 : size(gpsHz, 1);
end

if nargin < 2 || isempty(prnList)
    finiteCount = sum(isfinite(gpsHz), 2);
    [~, order] = sort(finiteCount, 'descend');
    keepN = min(4, numel(order));
    idxKeep = sort(order(1:keepN));
    prnList = prnPool(idxKeep);
else
    prnList = prnList(:)';
end

alarmIdx = [];
if isfield(navResults, 'spoofAlarm')
    alarmIdx = find(navResults.spoofAlarm, 1, 'first');
end

outDir = fullfile(projectRoot, 'deepIntegration', 'figures');
if exist(outDir, 'dir') ~= 7
    mkdir(outDir);
end

[~, baseName, ~] = fileparts(resultFile);
scenarioLabel = localScenarioLabel(S, baseName);

figPaths = {};
for i = 1 : numel(prnList)
    prn = prnList(i);
    idx = find(prnPool == prn, 1, 'first');
    if isempty(idx)
        warning('PRN %d not found in result, skipped.', prn);
        continue;
    end

    g = gpsHz(idx, :);
    ins = insHz(idx, :);
    cmb = cmbHz(idx, :);

    f = figure('Visible', 'off');
    tl = tiledlayout(2, 1, 'TileSpacing', 'compact', 'Padding', 'compact');

    nexttile;
    plot(t, g, 'b-', 'LineWidth', 1.1);
    hold on;
    plot(t, ins, 'r-', 'LineWidth', 1.1);
    grid on;
    ylabel('Doppler (Hz)');
    title(sprintf('%s PRN %d: GNSS vs INS', scenarioLabel, prn), 'Interpreter', 'none');
    legend({'GNSS measured', 'INS generated'}, 'Location', 'best', 'Interpreter', 'none');
    if ~isempty(alarmIdx) && alarmIdx <= numel(t)
        xline(t(alarmIdx), 'm--', 'Alarm');
    end

    nexttile;
    plot(t, ins, 'r-', 'LineWidth', 1.1);
    hold on;
    plot(t, cmb, 'k-', 'LineWidth', 1.1);
    grid on;
    ylabel('Doppler (Hz)');
    xlabel('Time (s)');
    title(sprintf('%s PRN %d: INS vs Combined', scenarioLabel, prn), 'Interpreter', 'none');
    legend({'INS generated', 'Combined navigation'}, 'Location', 'best', 'Interpreter', 'none');
    if ~isempty(alarmIdx) && alarmIdx <= numel(t)
        xline(t(alarmIdx), 'm--', 'Alarm');
    end

    title(tl, sprintf('%s Doppler Comparison PRN %d', scenarioLabel, prn), 'Interpreter', 'none');
    outPng = fullfile(outDir, sprintf('%s_doppler_gps_ins_combined_prn%02d.png', baseName, prn));
    exportgraphics(f, outPng, 'Resolution', 180);
    close(f);
    figPaths{end + 1} = outPng; %#ok<AGROW>
end

fprintf('\nSaved Doppler comparison figures:\n');
for i = 1 : numel(figPaths)
    fprintf('  %s\n', figPaths{i});
end
fprintf('\n');
end

function label = localScenarioLabel(S, baseName)
label = baseName;
if isfield(S, 'summary') && isstruct(S.summary) && isfield(S.summary, 'datasetTag')
    tag = char(S.summary.datasetTag);
    if isfield(S.summary, 'profile')
        label = sprintf('%s / %s', upper(tag), upper(char(S.summary.profile)));
    else
        label = upper(tag);
    end
end
end
